./run.pl -cfg ./Free45PDK_cfg/AND2X1.cfg
./run.pl -cfg ./Free45PDK_cfg/AND2X2.cfg
./run.pl -cfg ./Free45PDK_cfg/AOI21X1.cfg
./run.pl -cfg ./Free45PDK_cfg/AOI22X1.cfg
./run.pl -cfg ./Free45PDK_cfg/BUFX2.cfg
./run.pl -cfg ./Free45PDK_cfg/BUFX4.cfg
./run.pl -cfg ./Free45PDK_cfg/CLKBUF1.cfg
./run.pl -cfg ./Free45PDK_cfg/CLKBUF2.cfg
./run.pl -cfg ./Free45PDK_cfg/CLKBUF3.cfg
./run.pl -cfg ./Free45PDK_cfg/DFFNEGX1.cfg
./run.pl -cfg ./Free45PDK_cfg/DFFPOSX1.cfg
./run.pl -cfg ./Free45PDK_cfg/DFFSR.cfg
./run.pl -cfg ./Free45PDK_cfg/FAX1.cfg
./run.pl -cfg ./Free45PDK_cfg/HAX1.cfg
./run.pl -cfg ./Free45PDK_cfg/INVX1.cfg
./run.pl -cfg ./Free45PDK_cfg/INVX2.cfg
./run.pl -cfg ./Free45PDK_cfg/INVX4.cfg
./run.pl -cfg ./Free45PDK_cfg/INVX8.cfg
./run.pl -cfg ./Free45PDK_cfg/LATCH.cfg
./run.pl -cfg ./Free45PDK_cfg/MUX2X1.cfg
./run.pl -cfg ./Free45PDK_cfg/NAND2X1.cfg
./run.pl -cfg ./Free45PDK_cfg/NAND3X1.cfg
./run.pl -cfg ./Free45PDK_cfg/NOR2X1.cfg
./run.pl -cfg ./Free45PDK_cfg/NOR3X1.cfg
./run.pl -cfg ./Free45PDK_cfg/OAI21X1.cfg
./run.pl -cfg ./Free45PDK_cfg/OR2X1.cfg
./run.pl -cfg ./Free45PDK_cfg/OR2X2.cfg
./run.pl -cfg ./Free45PDK_cfg/XNOR2X1.cfg
./run.pl -cfg ./Free45PDK_cfg/XOR2X1.cfg
